// <auto-generated />
using System;
using CabinPlanner.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CabinPlanner.DataAccess.Migrations
{
    [DbContext(typeof(CabinPlannerContext))]
    [Migration("20190530234248_addedCalendarTrip")]
    partial class addedCalendarTrip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CabinPlanner.Model.Cabin", b =>
                {
                    b.Property<int>("CabinId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CabinName");

                    b.Property<int?>("CabinOwnerPersonId");

                    b.Property<int?>("CalendarId");

                    b.HasKey("CabinId");

                    b.HasIndex("CabinOwnerPersonId");

                    b.HasIndex("CalendarId");

                    b.ToTable("Cabin");
                });

            modelBuilder.Entity("CabinPlanner.Model.CabinUser", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("CabinId");

                    b.HasKey("PersonId", "CabinId");

                    b.HasIndex("CabinId");

                    b.ToTable("CabinUser");
                });

            modelBuilder.Entity("CabinPlanner.Model.Calendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CalendarId");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("CabinPlanner.Model.CalendarTrip", b =>
                {
                    b.Property<int>("CalendarId");

                    b.Property<int>("PlannedTripId");

                    b.HasKey("CalendarId", "PlannedTripId");

                    b.HasIndex("PlannedTripId");

                    b.ToTable("CalendarTrip");
                });

            modelBuilder.Entity("CabinPlanner.Model.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FamiliyName");

                    b.HasKey("FamilyId");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("CabinPlanner.Model.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalendarId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("FamilyId");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsMan");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("PersonId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("CabinPlanner.Model.PlannedTrip", b =>
                {
                    b.Property<int>("PlannedTripId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<DateTime>("FromDate");

                    b.Property<int>("PersonId");

                    b.Property<DateTime>("ToDate");

                    b.HasKey("PlannedTripId");

                    b.HasIndex("PersonId");

                    b.ToTable("PlannedTrip");
                });

            modelBuilder.Entity("CabinPlanner.Model.Cabin", b =>
                {
                    b.HasOne("CabinPlanner.Model.Person", "CabinOwner")
                        .WithMany()
                        .HasForeignKey("CabinOwnerPersonId");

                    b.HasOne("CabinPlanner.Model.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");
                });

            modelBuilder.Entity("CabinPlanner.Model.CabinUser", b =>
                {
                    b.HasOne("CabinPlanner.Model.Cabin", "Cabin")
                        .WithMany("CabinUsers")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CabinPlanner.Model.Person", "Person")
                        .WithMany("AccessToCabins")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CabinPlanner.Model.CalendarTrip", b =>
                {
                    b.HasOne("CabinPlanner.Model.Calendar", "Calendar")
                        .WithMany("PlannedTrips")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CabinPlanner.Model.PlannedTrip", "PlannedTrip")
                        .WithMany("TripCalendars")
                        .HasForeignKey("PlannedTripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CabinPlanner.Model.Person", b =>
                {
                    b.HasOne("CabinPlanner.Model.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");

                    b.HasOne("CabinPlanner.Model.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId");
                });

            modelBuilder.Entity("CabinPlanner.Model.PlannedTrip", b =>
                {
                    b.HasOne("CabinPlanner.Model.Person", "Planner")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
