// <auto-generated />
using System;
using CabinPlanner.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CabinPlanner.DataAccess.Migrations
{
    [DbContext(typeof(CabinPlannerContext))]
    partial class CabinPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CabinPlanner.Model.Cabin", b =>
                {
                    b.Property<int>("CabinId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CabinName");

                    b.Property<int?>("CabinOwnerPersonId");

                    b.Property<int?>("CalendarId");

                    b.HasKey("CabinId");

                    b.HasIndex("CabinOwnerPersonId");

                    b.HasIndex("CalendarId");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("CabinPlanner.Model.CabinsUsers", b =>
                {
                    b.Property<int>("CabinsUsersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CabinId");

                    b.Property<int?>("PersonId");

                    b.HasKey("CabinsUsersId");

                    b.HasIndex("CabinId");

                    b.HasIndex("PersonId");

                    b.ToTable("CabinsUsers");
                });

            modelBuilder.Entity("CabinPlanner.Model.Calendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CalendarId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("CabinPlanner.Model.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FamiliyName");

                    b.HasKey("FamilyId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("CabinPlanner.Model.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalendarId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<int?>("FamilyId");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsMan");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("PersonId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("FamilyId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CabinPlanner.Model.PlannedTrip", b =>
                {
                    b.Property<int>("PlannedTripId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalendarId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("FromDate");

                    b.Property<int?>("PlannerPersonId");

                    b.Property<DateTime>("ToDate");

                    b.HasKey("PlannedTripId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("PlannerPersonId");

                    b.ToTable("PlannedTrips");
                });

            modelBuilder.Entity("CabinPlanner.Model.Cabin", b =>
                {
                    b.HasOne("CabinPlanner.Model.Person", "CabinOwner")
                        .WithMany()
                        .HasForeignKey("CabinOwnerPersonId");

                    b.HasOne("CabinPlanner.Model.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");
                });

            modelBuilder.Entity("CabinPlanner.Model.CabinsUsers", b =>
                {
                    b.HasOne("CabinPlanner.Model.Cabin", "Cabin")
                        .WithMany()
                        .HasForeignKey("CabinId");

                    b.HasOne("CabinPlanner.Model.Person", "person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("CabinPlanner.Model.Person", b =>
                {
                    b.HasOne("CabinPlanner.Model.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId");

                    b.HasOne("CabinPlanner.Model.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId");
                });

            modelBuilder.Entity("CabinPlanner.Model.PlannedTrip", b =>
                {
                    b.HasOne("CabinPlanner.Model.Calendar")
                        .WithMany("PlannedTrips")
                        .HasForeignKey("CalendarId");

                    b.HasOne("CabinPlanner.Model.Person", "Planner")
                        .WithMany()
                        .HasForeignKey("PlannerPersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
